/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_CONFDIR "/usr/local/etc/qemu"
#define CONFIG_QEMU_DATADIR "/usr/local/share/qemu"
#define CONFIG_QEMU_DOCDIR "/usr/local/share/doc/qemu"
#define CONFIG_QEMU_MODDIR "/usr/local/lib/qemu"
#define CONFIG_QEMU_LOCALSTATEDIR "/usr/local/var"
#define CONFIG_QEMU_HELPERDIR "/usr/local/libexec"
#define CONFIG_QEMU_LOCALEDIR "/usr/local/share/locale"
#define HOST_ARM 1
#define CONFIG_POSIX 1
#define CONFIG_LINUX 1
// #define CONFIG_SLIRP 0
#define CONFIG_SMBD_COMMAND "/usr/sbin/smbd"

#define CONFIG_BDRV_RW_WHITELIST\
    NULL
#define CONFIG_BDRV_RO_WHITELIST\
    NULL
// #define CONFIG_VNC 1
#define CONFIG_FNMATCH 1
#define QEMU_VERSION "2.7.0"
// #define CONFIG_PIPE2 0
// #define CONFIG_EVENTFD 0
// #define CONFIG_EPOLL 0
// #define CONFIG_SENDFILE 0
// #define CONFIG_INOTIFY 0
#define CONFIG_BYTESWAP_H 1
#define CONFIG_TLS_PRIORITY "NORMAL"
#define CONFIG_IOVEC 1
// #define CONFIG_FDT 0
// #define CONFIG_FDATASYNC 0
#define CONFIG_MADVISE 1
#define CONFIG_COROUTINE_BACKEND sigaltstack
#define CONFIG_COROUTINE_POOL 1
#define CONFIG_LINUX_MAGIC_H 1
#define CONFIG_PRAGMA_DIAGNOSTIC_AVAILABLE 1
// #define CONFIG_HAS_ENVIRON 0
// #define CONFIG_TRACE_LOG 0
#define CONFIG_TRACE_FILE trace
#define CONFIG_THREAD_SETNAME_BYTHREAD 1
#define CONFIG_PTHREAD_SETNAME_NP 1
#define HOST_DSOSUF ".so"
